package bd6.gui.client;

import bd6.Main;
import bd6.data.Client;
import bd6.data.Item;
import bd6.data.Order;
import bd6.util.Pair;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class NewOrderFrame extends javax.swing.JFrame {
    protected TableModel itemTableModel;
    protected NewOrderContentsTableModel newOrderTableModel;

    /**
     * Creates new form NewOrderFrame
     */
    public NewOrderFrame() {
        itemTableModel = new ItemTableModel();
        newOrderTableModel = new NewOrderContentsTableModel();

        initComponents();
    }

    public TableModel getItemTableModel() {
        return itemTableModel;
    }

    public TableModel getNewOrderContentsTableModel() {
        return newOrderTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderContentsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        shippingDateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Order");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("Press ENTER to add an item below to your order:");

        itemTable.setModel(getItemTableModel());
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        itemTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        orderContentsTable.setModel(getNewOrderContentsTableModel());
        orderContentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderContentsTableMouseClicked(evt);
            }
        });
        orderContentsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                orderContentsTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(orderContentsTable);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("Press DELETE to remove an item from your order:");

        totalAmountLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        totalAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalAmountLabel.setText("EUR 0");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total amount:");

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jLabel4.setText("Shipping Date (YYYY-MM-DD):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shippingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(shippingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTableKeyPressed
        if (evt != null)
            if (evt.getKeyCode() != KeyEvent.VK_ENTER)
                return;

        int[] selection = itemTable.getSelectedRows();

        for (int i : selection) {
            Item item = (Item) itemTableModel.getValueAt(i, -1);

            newOrderTableModel.addItem(item);
        }

        totalAmountLabel.setText("EUR " + Integer.toString(newOrderTableModel.getTotalValue()));
    }//GEN-LAST:event_itemTableKeyPressed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        OrdersFrame ordersFrame = new OrdersFrame();

        Main.centerFrame(ordersFrame);
        ordersFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date buffer = formatter.parse(shippingDateField.getText());
            Date shippingDate = new Date(buffer.getTime());
            ArrayList<Pair<Item, Integer>> contents = newOrderTableModel.getItems();
            Order order = new Order((Client) Main.currentUser, contents, shippingDate);

            order.commit();

            String message = "The order has been successfully created!";

            JOptionPane.showMessageDialog(null, message, "Information",
                                          JOptionPane.INFORMATION_MESSAGE);
            cancelButtonMouseClicked(null);
        } catch (ParseException exception) {
            String message = "Invalid shipping date format!";

            JOptionPane.showMessageDialog(this, message, "Error",
                                          JOptionPane.ERROR_MESSAGE);
            return;
        } catch (SQLException exception) {
            String message = "Error while adding the order.";

            System.err.println("Fatal Error:");
            exception.printStackTrace();
            JOptionPane.showMessageDialog(this, message, "Database Error",
                                          JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }//GEN-LAST:event_okButtonMouseClicked

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        if (evt.getClickCount() == 2)
            itemTableKeyPressed(null);
    }//GEN-LAST:event_itemTableMouseClicked

    private void orderContentsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderContentsTableKeyPressed
        if (evt != null && evt.getKeyCode() != KeyEvent.VK_DELETE)
            return;

        int[] selection = orderContentsTable.getSelectedRows();

        for (int i = 0; i < selection.length; ++i) {
            newOrderTableModel.removeItem(selection[i]);

            for (int j = i; j < selection.length; ++j)
                selection[j]--;
        }

        totalAmountLabel.setText("EUR " + Integer.toString(newOrderTableModel.getTotalValue()));
    }//GEN-LAST:event_orderContentsTableKeyPressed

    private void orderContentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderContentsTableMouseClicked
        if (evt.getClickCount() == 2)
            orderContentsTableKeyPressed(null);
    }//GEN-LAST:event_orderContentsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton okButton;
    private javax.swing.JTable orderContentsTable;
    private javax.swing.JTextField shippingDateField;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables
}
