package bd6.gui.manager;

import bd6.Main;
import bd6.data.Packer;
import bd6.gui.LoginFrame;
import javax.swing.table.TableModel;

public class PeopleFrame extends javax.swing.JFrame {
    protected PeopleTableModel peopleTableModel;

    /**
     * Creates new form PeopleFrame
     */
    public PeopleFrame() {
        peopleTableModel = new PeopleTableModel();
        initComponents();
    }

    public TableModel getPeopleTableModel() {
        return peopleTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        topSellsMenuItem = new javax.swing.JMenuItem();
        itemListMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("People Explorer");
        setResizable(false);

        peopleTable.setModel(getPeopleTableModel());
        peopleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(peopleTable);

        jMenu1.setText("Action");

        topSellsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        topSellsMenuItem.setText("Display Top Sells");
        topSellsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topSellsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(topSellsMenuItem);

        itemListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemListMenuItem.setText("Display Item List");
        itemListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(itemListMenuItem);

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        LoginFrame loginFrame = new LoginFrame();

        Main.centerFrame(loginFrame);
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void peopleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleTableMouseClicked
        if (evt.getClickCount() != 2)
            return;

        int selection = peopleTable.getSelectedRow();
        Object user = peopleTableModel.getValueAt(selection, -1);

        if (user instanceof Packer) {
            EmployeeFrame employeeForm = new EmployeeFrame((Packer) user);

            Main.centerFrame(employeeForm);
            employeeForm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_peopleTableMouseClicked

    private void topSellsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topSellsMenuItemActionPerformed
        TopSellsFrame topSellsFrame = new TopSellsFrame();

        Main.centerFrame(topSellsFrame);
        topSellsFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_topSellsMenuItemActionPerformed

    private void itemListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListMenuItemActionPerformed
        ItemFrame itemFrame = new ItemFrame();

        Main.centerFrame(itemFrame);
        itemFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemListMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem itemListMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JTable peopleTable;
    private javax.swing.JMenuItem topSellsMenuItem;
    // End of variables declaration//GEN-END:variables
}
