package bd6.gui.customs;

import bd6.Main;
import bd6.data.Package;
import bd6.gui.LoginFrame;
import javax.swing.table.TableModel;

public class PackageListFrame extends javax.swing.JFrame {
    protected TableModel packageTableModel;

    public PackageListFrame() {
        packageTableModel = new PackagesTableModel();
        initComponents();
    }

    public TableModel getPackageTableModel() {
        return packageTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packageTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        actionMenu = new javax.swing.JMenu();
        statisticsMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        checkedPackagesMenuItem = new javax.swing.JMenuItem();
        uncheckedPackagesMenuItem = new javax.swing.JMenuItem();
        allPackagesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Package Explorer - Unchecked Packages");
        setResizable(false);

        packageTable.setModel(getPackageTableModel());
        packageTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(packageTable);

        actionMenu.setText("Action");

        statisticsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        statisticsMenuItem.setText("Statistics");
        statisticsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsMenuItemActionPerformed(evt);
            }
        });
        actionMenu.add(statisticsMenuItem);

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        actionMenu.add(logoutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        actionMenu.add(exitMenuItem);

        jMenuBar1.add(actionMenu);

        viewMenu.setText("View");

        checkedPackagesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        checkedPackagesMenuItem.setText("Checked Packages");
        checkedPackagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedPackagesMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(checkedPackagesMenuItem);

        uncheckedPackagesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        uncheckedPackagesMenuItem.setText("Unchecked Packages");
        uncheckedPackagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uncheckedPackagesMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(uncheckedPackagesMenuItem);

        allPackagesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        allPackagesMenuItem.setText("All Packages");
        allPackagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allPackagesMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(allPackagesMenuItem);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        LoginFrame loginFrame = new LoginFrame();

        Main.centerFrame(loginFrame);
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void uncheckedPackagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uncheckedPackagesMenuItemActionPerformed
        packageTableModel = new PackagesTableModel();

        packageTable.setModel(packageTableModel);
        setTitle("Package Explorer - Unchecked Packages");
    }//GEN-LAST:event_uncheckedPackagesMenuItemActionPerformed

    private void allPackagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allPackagesMenuItemActionPerformed
        packageTableModel = new AllPackagesTableModel();

        packageTable.setModel(packageTableModel);
        setTitle("Package Explorer - All Packages");
    }//GEN-LAST:event_allPackagesMenuItemActionPerformed

    private void packageTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageTableMouseClicked
        int selection = packageTable.getSelectedRow();
        Package pkg = (Package) packageTableModel.getValueAt(selection, -1);

        if (evt.getClickCount() == 2) {
            PackageFrame packageFrame = new PackageFrame(pkg);

            Main.centerFrame(packageFrame);
            packageFrame.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_packageTableMouseClicked

    private void checkedPackagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedPackagesMenuItemActionPerformed
        packageTableModel = new PackagesTableModel(true);

        packageTable.setModel(packageTableModel);
        setTitle("Package Explorer - Checked Packages");
    }//GEN-LAST:event_checkedPackagesMenuItemActionPerformed

    private void statisticsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsMenuItemActionPerformed
        StatisticsFrame statisticsFrame = new StatisticsFrame();

        Main.centerFrame(statisticsFrame);
        statisticsFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_statisticsMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private javax.swing.JMenuItem allPackagesMenuItem;
    private javax.swing.JMenuItem checkedPackagesMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JTable packageTable;
    private javax.swing.JMenuItem statisticsMenuItem;
    private javax.swing.JMenuItem uncheckedPackagesMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
