/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bd6.gui.customs;

import bd6.Main;
import bd6.data.Customs;
import bd6.data.Package;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Grégoire Duchêne
 */
public class StatisticsFrame extends javax.swing.JFrame {
    protected int globalPackageNumber;
    protected int globalCheckedPackageNumber;
    protected int globalCheckedPackagePercentage;
    protected int localPackageNumber;
    protected int localCheckedPackageNumber;
    protected int localAcceptedPackageNumber;
    protected int localRejectedPackageNumber;
    protected int localCheckedPackagePercentage;
    protected double localRatio;

    public StatisticsFrame() {
        String country = ((Customs) Main.currentUser).getCountry();

        try {
            ArrayList<Package> packages = Package.get();

            for (Package pkg : packages) {
                globalPackageNumber++;

                if (pkg.getControlDate() != null) {
                    globalCheckedPackageNumber++;

                    if (pkg.getCountry().equals(country)) {
                        localPackageNumber++;
                        localCheckedPackageNumber++;

                        switch (pkg.getControlStatus()) {
                        case OK:
                            localAcceptedPackageNumber++;
                            break;

                        case KO:
                            localRejectedPackageNumber++;
                            break;

                        default:
                            break;
                        }
                    }
                } else if (pkg.getCountry().equals(country))
                    localPackageNumber++;


            }

            if (globalPackageNumber > 0)
                globalCheckedPackagePercentage = (int) ((double) globalCheckedPackageNumber
                                                        / globalPackageNumber * 100);
            else
                globalCheckedPackagePercentage = 0;

            if (localPackageNumber > 0)
                localCheckedPackagePercentage = (int) ((double) localCheckedPackageNumber
                                                       / localPackageNumber * 100);
            else
                localCheckedPackagePercentage = 0;

            if (localRejectedPackageNumber > 0)
                localRatio = ((double) localAcceptedPackageNumber
                              / localRejectedPackageNumber);
            else
                localRatio = localAcceptedPackageNumber;

        } catch (SQLException exception) {
            String message = "A database error occurred while fetching "
                             + "statistics.";

            System.err.println("Fatal Error:");
            exception.printStackTrace();
            JOptionPane.showMessageDialog(null, message, "Database Error",
                                          JOptionPane.ERROR_MESSAGE);

        }

        initComponents();

        globalPackageNumberLabel.setText(Integer.toString(globalPackageNumber));
        globalCheckedPackageNumberLabel.setText(Integer.toString(globalCheckedPackageNumber));
        globalCheckedPackagePercentageLabel.setText(Integer.toString(globalCheckedPackagePercentage) + '%');
        localPackageNumberLabel.setText(Integer.toString(localPackageNumber));
        localCheckedPackageNumberLabel.setText(Integer.toString(localCheckedPackageNumber));
        localAcceptedPackageNumberLabel.setText(Integer.toString(localAcceptedPackageNumber));
        localRejectedPackageNumberLabel.setText(Integer.toString(localRejectedPackageNumber));
        localCheckedPackagePercentageLabel.setText(Integer.toString(localCheckedPackagePercentage) + '%');
        localRatioLabel.setText(Double.toString(localRatio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        localRatioLabel = new javax.swing.JLabel();
        localCheckedPackagePercentageLabel = new javax.swing.JLabel();
        localRejectedPackageNumberLabel = new javax.swing.JLabel();
        localAcceptedPackageNumberLabel = new javax.swing.JLabel();
        localCheckedPackageNumberLabel = new javax.swing.JLabel();
        localPackageNumberLabel = new javax.swing.JLabel();
        globalCheckedPackagePercentageLabel = new javax.swing.JLabel();
        globalCheckedPackageNumberLabel = new javax.swing.JLabel();
        globalPackageNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistics");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("General Figures");

        jLabel2.setText("Number of packages:");

        jLabel3.setText("Number of checked packages:");

        jLabel4.setText("Percentage of checked packages:");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setText("Your Country's Customs Figures");

        jLabel6.setText("Number of packages:");

        jLabel7.setText("Number of checked packages:");

        jLabel8.setText("Number of accepted packages:");

        jLabel9.setText("Number of rejected packages:");

        jLabel10.setText("Percentage of checked packages:");

        jLabel11.setText("Ratio accepted / rejected packages:");

        closeButton.setText("Close");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        localRatioLabel.setText("jLabel12");

        localCheckedPackagePercentageLabel.setText("jLabel12");

        localRejectedPackageNumberLabel.setText("jLabel12");

        localAcceptedPackageNumberLabel.setText("jLabel12");

        localCheckedPackageNumberLabel.setText("jLabel12");

        localPackageNumberLabel.setText("jLabel12");

        globalCheckedPackagePercentageLabel.setText("jLabel12");

        globalCheckedPackageNumberLabel.setText("jLabel12");

        globalPackageNumberLabel.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator2)
                                    .addComponent(localRatioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(localCheckedPackagePercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(localRejectedPackageNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(localAcceptedPackageNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(localCheckedPackageNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(localPackageNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(globalCheckedPackagePercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(globalCheckedPackageNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(globalPackageNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(globalPackageNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(globalCheckedPackageNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(globalCheckedPackagePercentageLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(localPackageNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(localCheckedPackageNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(localAcceptedPackageNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(localRejectedPackageNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(localCheckedPackagePercentageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(localRatioLabel))
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        PackageListFrame packageListFrame = new PackageListFrame();

        Main.centerFrame(packageListFrame);
        packageListFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeButtonMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel globalCheckedPackageNumberLabel;
    private javax.swing.JLabel globalCheckedPackagePercentageLabel;
    private javax.swing.JLabel globalPackageNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel localAcceptedPackageNumberLabel;
    private javax.swing.JLabel localCheckedPackageNumberLabel;
    private javax.swing.JLabel localCheckedPackagePercentageLabel;
    private javax.swing.JLabel localPackageNumberLabel;
    private javax.swing.JLabel localRatioLabel;
    private javax.swing.JLabel localRejectedPackageNumberLabel;
    // End of variables declaration//GEN-END:variables
}
